services:
- name: scheduler-app
  type: web
  build:
    type: docker
  instance_type: nano
  ports:
  - port: 8000
    protocol: http
  health_check:
    path: /api/health
    port: 8000
    initial_delay: 30s
    interval: 10s
    timeout: 5s
    retries: 3
  env:
  - key: NODE_ENV
    value: production